### ISSUE TITLE
fix this 

### ISSUE THREAD

**Issue by RAOUMERTC73** [merldsu/RISCV_Single-_Cycle_Core#2]
It does not support branch instruction in the YouTube video lecture, and the sign extend does not support the b types instruction also your document does not add this type of datapath but in the read me file you give a complete  picture of single cycle processor.

**Comment by HamzaShabbir517** [comment]
@RAOUMERTC73 yes those things are left for the learner to implement. So that he can learn how to add new instructions in existing design and increase the functionality
